fix: validator will receive rewards on both their commission and thei…
5ire-tech/5ireChain pull request #150
Opened 2024-06-03 11:21 UTC by arunjot12

The validator will earn rewards from their commission, even if it's set at 0%, as well as from their stake.

2024-06-03 14:33 UTC, dung5ire approved these changes

2024-06-03 14:38 UTC, dung5ire requested changes
Kindly increase spec version for QA and GA @arunjot12

2024-06-04 04:42 UTC, arunjot12 commented
@dung5ire. I've increased the version.Please check

2024-06-04 04:50 UTC, dung5ire approved these changes

2024-06-04 05:19 UTC, s-h-ubham approved these changes

2024-06-04 07:32 UTC, merged